linters:
  disable-all: true
  enable:
  - deadcode
  - errcheck
  - gosimple
  - govet
  - ineffassign
  - misspell
  - nilerr
  - nolintlint
  - staticcheck
  - structcheck
  - typecheck
  - unused
  - varcheck

linters-settings:
  nolintlint:
    allow-unused: false
    allow-leading-space: false
    require-specific: true
  staticcheck:
    go: "1.19"
  stylecheck:
    go: "1.19"
  unused:
    go: "1.19"

run:
  timeout: 10m
  allow-parallel-runners: true

