name: test

on: push

jobs:
  gotest:
    if: github.event.pusher.name != 'dreamkast-cloudnativedays'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.19"
      - name: Run Test
        run: |
          make test
          git diff --exit-code
